package net.tds.magicpets;

import java.util.Arrays;

import net.minecraftforge.common.MinecraftForge;
import net.tds.magicpets.entity.pet.EntityBabyEarthTurtle;
import net.tds.magicpets.entity.pet.EntityBabyFireGolem;
import net.tds.magicpets.event.EntityConstructionEvent;
import net.tds.magicpets.handler.ConnectionHandler;
import net.tds.magicpets.item.Items;
import net.tds.magicpets.lib.Config;
import net.tds.magicpets.lib.Reference;
import net.tds.magicpets.proxy.CommonProxy;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;

//99% of these commits are for dev discussion and notification.

//I edited the image thing. Crashes everywhere if a null crystal was shown.

//We need a way for the mob do instantly die when its owner goes offline.

//We need to........
@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = true)
public class ModJam {
	
	@SidedProxy(serverSide = Reference.PROXY_SERVER, clientSide = Reference.PROXY_CLIENT)
	public static CommonProxy proxy;

	@Instance(Reference.MOD_ID)
	public static ModJam instance;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		
		getModInfo(event.getModMetadata());
		new Config(event.getSuggestedConfigurationFile());
		new Items();
		MinecraftForge.EVENT_BUS.register(new EntityConstructionEvent());
		
		EntityRegistry.registerModEntity(EntityBabyFireGolem.class, "golem", 4, this, 30, 5, true);
		EntityRegistry.registerModEntity(EntityBabyEarthTurtle.class, "turtle", 5, this, 30, 5, true);
		proxy.registerRenders();
	}
	
	@EventHandler
	public void init(FMLPreInitializationEvent event) {
		
		NetworkRegistry.instance().registerConnectionHandler(new ConnectionHandler());
	}
	
	public void getModInfo(ModMetadata meta) {
		
		meta.authorList = Arrays.asList("ThisGuy1045, Darkhax, ShadowChild, HoopAWolf");
		meta.logoFile = "/assets/modjam3/logo.png";
		meta.autogenerated = false;
		meta.description = "I can't tell you just yet ;p";
		meta.url = "www.darkhax.net/modjam.html";
	}
}
