package net.tds.magicpets;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraftforge.common.MinecraftForge;
import net.tds.magicpets.entity.EntityManager;
import net.tds.magicpets.entity.passive.EntityBabyEarthPet;
import net.tds.magicpets.entity.passive.EntityBabyFirePet;
import net.tds.magicpets.event.EntityConstructionEvent;
import net.tds.magicpets.event.ItemDropEvent;
import net.tds.magicpets.event.MobDeathEvent;
import net.tds.magicpets.handler.ConnectionHandler;
import net.tds.magicpets.handler.PlayerTracker;
import net.tds.magicpets.item.Items;
import net.tds.magicpets.lib.Config;
import net.tds.magicpets.lib.Reference;
import net.tds.magicpets.packet.PacketHandler;
import net.tds.magicpets.proxy.CommonProxy;

import java.util.Arrays;

//Pet crystals are dropped by the boss however they don't work. This NEEDS to be fixed
//Before the event ends. 


//Pet needs a way to check if its player is online if not despawn. **

//Pet needs a way to check if its player has its spawn item in its inv. if not despawn. **

//Pets need cooldown **


@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = true, channels = "maigcpets", packetHandler = PacketHandler.class)
public class ModJam {
	
	@SidedProxy(serverSide = Reference.PROXY_SERVER, clientSide = Reference.PROXY_CLIENT)
	public static CommonProxy proxy;

	@Instance(Reference.MOD_ID)
	public static ModJam instance;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		
		getModInfo(event.getModMetadata());
		new Config(event.getSuggestedConfigurationFile());
		new Items();
		new EntityManager(this);
		MinecraftForge.EVENT_BUS.register(new EntityConstructionEvent());	
		MinecraftForge.EVENT_BUS.register(new MobDeathEvent());
		MinecraftForge.EVENT_BUS.register(new ItemDropEvent());
		proxy.registerRenders();
	}
	
	@EventHandler
	public void init(FMLPreInitializationEvent event) {
		
		NetworkRegistry.instance().registerConnectionHandler(new ConnectionHandler());
	}
	
	public void getModInfo(ModMetadata meta) {
		
		meta.authorList = Arrays.asList("ThisGuy1045, Darkhax, ShadowChild, HoopAWolf");
		meta.logoFile = "/assets/magicpets/logo.png";
		meta.autogenerated = false;
		meta.description = "I can't tell you just yet ;p";
		meta.url = "www.darkhax.net/modjam.html";
	}
}
